on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  merge_group:
  pull_request:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          args: check --config ci.ruff.toml

  type-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup a local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-type-check-${{ hashFiles('poetry.lock') }}
      - uses: actions/cache@v3
        name: Cache mypy cache
        with:
          path: ./.mypy_cache
          key: mypy-${{ hashFiles('**/*.py', 'pyproject.toml') }}
          restore-keys: |
            mypy-
      - name: Install dependencies
        run: poetry install --only=main,dev
      - name: Run mypy type checking
        run: poetry run mypy ants-platform --no-error-summary

  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      ANTS_PLATFORM_HOST: "http://localhost:3000"
      ANTS_PLATFORM_PUBLIC_KEY: "pk-ap-1234567890"
      ANTS_PLATFORM_SECRET_KEY: "sk-ap-1234567890"
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      # SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
      HUGGINGFACEHUB_API_TOKEN: ${{ secrets.HUGGINGFACEHUB_API_TOKEN }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"

    name: Test on Python version ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 9.5.0

      - name: Clone ants-platform server
        run: |
          git clone https://github.com/ants-platform/ants-platform.git ./ants-platform-server && echo $(cd ./ants-platform-server && git rev-parse HEAD)

      - name: Setup node (for ants-platform server)
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache ants-platform server dependencies
        uses: actions/cache@v3
        with:
          path: ./ants-platform-server/node_modules
          key: |
            ants-platform-server-${{ hashFiles('./ants-platform-server/package-lock.json') }}
            ants-platform-server-

      - name: Run ants-platform server
        run: |
          cd ./ants-platform-server

          echo "::group::Run ants-platform server"
          TELEMETRY_ENABLED=false docker compose up -d postgres
          echo "::endgroup::"

          echo "::group::Logs from ants-platform server"
          TELEMETRY_ENABLED=false docker compose logs
          echo "::endgroup::"

          echo "::group::Install dependencies (necessary to run seeder)"
          pnpm i
          echo "::endgroup::"

          echo "::group::Seed db"
          cp .env.dev.example .env
          pnpm run db:migrate          
          pnpm run db:seed
          echo "::endgroup::"
          rm -rf .env

          echo "::group::Run server"

          TELEMETRY_ENABLED=false \
          ANTS_PLATFORM_S3_MEDIA_UPLOAD_ENDPOINT=http://localhost:9090 \
          ANTS_PLATFORM_INGESTION_QUEUE_DELAY_MS=10 \
          ANTS_PLATFORM_INGESTION_CLICKHOUSE_WRITE_INTERVAL_MS=10 \
          docker compose up -d

          echo "::endgroup::"

      # Add this step to check the health of the container
      - name: Health check for ants-platform server
        run: |
          echo "Checking if the ants-platform server is up..."
          retry_count=0
          max_retries=10
          until curl --output /dev/null --silent --head --fail http://localhost:3000/api/public/health
          do
            retry_count=`expr $retry_count + 1`
            echo "Attempt $retry_count of $max_retries..."
            if [ $retry_count -ge $max_retries ]; then
              echo "AntsPlatform server did not respond in time. Printing logs..."
              docker logs ants-platform-server-ants-platform-web-1
              echo "Failing the step..."
              exit 1
            fi
            sleep 5
          done
          echo "AntsPlatform server is up and running!"

      - name: Install Python
        uses: actions/setup-python@v4
        # see details (matrix, python-version, python-version-file, etc.)
        # https://github.com/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check python version
        run: python --version

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Set poetry python version
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry env info

      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: |
            venv-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}-${{ github.sha }}

      - name: Install the project dependencies
        run: poetry install --all-extras

      - name: Run the automated tests
        run: |
          python --version
          poetry run pytest -n auto --dist loadfile -s -v --log-cli-level=INFO

  all-tests-passed:
    # This allows us to have a branch protection rule for tests and deploys with matrix
    runs-on: ubuntu-latest
    needs: [ci, linting, type-checking]
    if: always()
    steps:
      - name: Successful deploy
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failing deploy
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
